# Site settings
title: Nexii
email: martin.r.pitt@gmail.com
description: >-
    I'm Nexii, also known as Martin, a London-based Web Developer
    with a passion for humanity, game development and technology.
baseurl: ""
url: "https://nexii.dev"
twitter_username: Nexii
github_username:  Martin-Pitt

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
keep_files: ["assets/"]

# Serve Settings
port: 1500


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
